package weather;

public enum Sensor {
  UP_TEMP,
  UP_HUMIDITY,
  UP_VOC,
  DOWN_TEMP,
  DOWN_HUMIDITY,
  DOWN_VOC,
  FRONT_TEMP,
  FRONT_HUMIDITY,
  FRONT_PRESSURE,
  FRONT_VOC,
  BACK_TEMP,
  DECK_TEMP,
  POOL_TEMP,
  GARAGE_TEMP,
  GARAGE_HUMIDITY,
  GARAGE_PRESSURE,
  GARAGE_VOC,
}
